apiVersion: v2
name: secrets-store-csi-driver-provider-1password
description: A Helm chart to install Google Secret Manager Provider for Secret Store CSI Driver inside a Kubernetes cluster.
type: application
version: 0.1.0
appVersion: "0.1.0"
