nameOverride: ""

serviceAccount:
  annotations: {}
  name: secrets-store-csi-driver-provider-1password

image:
  repository: us-docker.pkg.dev/secretmanager-csi/secrets-store-csi-driver-provider-1password/plugin
  pullPolicy: IfNotPresent
  tag: latest

connect:
  server: http://myconnectserver.mynamespace.svc.cluster.local:8080/

# if tokenLiteral is not empty, creates a secret from the literal below
# if tokenLiteral is empty, assumes that you will create the secret yourself
secret:
  tokenLiteral: ""
  secretName: 1password-connect-token
  secretKey: token

app: csi-secrets-store-provider-1password

podAnnotations: {}

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 50m
    memory: 100Mi

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
