nameOverride: ""

serviceAccount:
  annotations: {}
  name: secrets-store-csi-driver-provider-1password

image:
  repository: us-docker.pkg.dev/secretmanager-csi/secrets-store-csi-driver-provider-1password/plugin
  pullPolicy: IfNotPresent
  tag: latest

connect:
  token: CREATEME123
  server: http://myconnectserver.mynamespace.svc.cluster.local:8080/

app: csi-secrets-store-provider-1password

podAnnotations: {}

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 50m
    memory: 100Mi

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
