{{ if not (eq .Values.secret.tokenLiteral "") }}
apiVersion: v1
data:
  {{ .Values.secret.secretKey }}: {{ .Values.secret.tokenLiteral | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
{{ end }}